ARG BASE_TAG="develop"
ARG BASE_IMAGE="kasmweb_core-ubuntu-jammy"
FROM registry.cn-hangzhou.aliyuncs.com/reg_pub/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# arm
# COPY ./pkgs/arm-sources.list /etc/apt/sources.list
# amd64
COPY ./pkgs/sources.list /etc/apt/sources.list

# Install Chromium
COPY ./src/ubuntu/install/chromium $INST_SCRIPTS/chromium/
RUN bash $INST_SCRIPTS/chromium/install_chromium.sh && rm -rf $INST_SCRIPTS/chromium/

# mcp 
# 定义环境变量
ENV UV_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
ENV EXTRA_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
ENV UV_DEFAULT_INDEX=https://pypi.tuna.tsinghua.edu.cn/simple
ENV UV_PYTHON_INSTALL_MIRROR=https://mirror.nju.edu.cn/github-release/indygreg/python-build-standalone/
ENV WEB_DIR=/home/kasm-user/app
ENV MCP_CONFIG=$WEB_DIR/config 
ENV BROWER_USER_DIR=$WEB_DIR/brower-user-dir  
ENV WEB_PYTHON_ENV=$WEB_DIR/mcp-env
ENV WEB_LOG=$WEB_DIR/log


RUN mkdir -p ${BROWER_USER_DIR} && \
    mkdir -p $WEB_LOG && \
    mkdir -p $MCP_CONFIG 

COPY ./mcp/start.sh        ${STARTUPDIR}/custom_startup.sh
COPY ./mcp/config.json     ${MCP_CONFIG}/
COPY ./pkgs/nodesource_setup.sh      ${MCP_CONFIG}/nodesource_setup.sh   

# 安装nodejs和pip
# 
RUN chmod +x ${MCP_CONFIG}/nodesource_setup.sh && \
    chmod +x ${STARTUPDIR}/custom_startup.sh && \
    bash ${MCP_CONFIG}/nodesource_setup.sh && apt-get update && \
    apt-get install -y --no-install-recommends nodejs  python3-pip&& \
    rm -rf /var/lib/apt/lists/* && rm -f ${MCP_CONFIG}/nodesource_setup.sh
RUN pip install uv -i  $UV_INDEX_URL && \
uv venv $WEB_PYTHON_ENV --python 3.12  && \
. $WEB_PYTHON_ENV/bin/activate && \
uv pip install playwright mcpo 

# RUN $STARTUPDIR/set_user_permission.sh $WEB_DIR && $STARTUPDIR/set_user_permission.sh $WEB_LOG  && chown -R 1000:0 $WEB_DIR  &&\
#     chown -R 1000:0 $WEB_LOG && \
#     chown -R 1000:0 $WEB_DIR/config



######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
# CMD [ "${WEB_DIR}/start.sh" ]
# CMD ["--tail-log"]