
services:
  mcp-server:
    container_name: mcp-server
    image: mcp-server:v0.2
    build:
      context: .
      dockerfile: mcp-servers-dockerfile
    network_mode: host
    ipc: host
    volumes:
      - ./mcps:/workerspace/mcps
      - ./data:/workerspace/data
     
    