services:
  web:
    container_name: web
    image: web:v1.2
    shm_size: 512m
    build:
      context: .
      dockerfile: web-dockerfile
    ipc: host
    # user: root 
    privileged: true
    # volumes:
    #   - ~/Desktop/web-data/log:/home/kasm-user/app/log
    ports:
      - "6901:6901"
      - "8002:8002"
      - "8001:8001"
      - "8003:8003"
    environment:
      - VNC_PW=132632
    restart: unless-stopped
    # command: ["${WEB_DIR}/start.sh"]